# DO NOT EDIT THIS FILE!
#
# Python module wordy_idl generated by omniidl

import omniORB
omniORB.updateModule("wordy_idl")

# ** 1. Stub files contributing to this module
import Wordy_idl

# ** 2. Sub-modules

# ** 3. End
