package wordy_idl;

/**
* wordy_idl/LoggedInExceptionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/

public final class LoggedInExceptionHolder implements org.omg.CORBA.portable.Streamable
{
  public wordy_idl.LoggedInException value = null;

  public LoggedInExceptionHolder ()
  {
  }

  public LoggedInExceptionHolder (wordy_idl.LoggedInException initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordy_idl.LoggedInExceptionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordy_idl.LoggedInExceptionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordy_idl.LoggedInExceptionHelper.type ();
  }

}
