package wordy_idl;


/**
* wordy_idl/WordLengthException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/

public final class WordLengthException extends org.omg.CORBA.UserException
{

  public WordLengthException ()
  {
    super(WordLengthExceptionHelper.id());
  } // ctor


  public WordLengthException (String $reason)
  {
    super(WordLengthExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class WordLengthException
