package wordy_idl;


/**
* wordy_idl/GameMenuServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/


// Interface for the Game Menu Servant object
public interface GameMenuServantOperations 
{
  void gameStarted ();
  void playersUpdated (int[] players);
  int logIn (String username, String password) throws wordy_idl.InvalidPasswordException, wordy_idl.NoUserFoundException, wordy_idl.LoggedInException, wordy_idl.IncompleteCredentialsException;
  void startGame () throws wordy_idl.NoPlayersJoinedException;
  String[] getBestPlayers ();
  String[] getLongestWords ();
  void logOut (String username);
  int updateCountdown (int value);
  int inQueue ();
} // interface GameMenuServantOperations
