package wordy_idl;


/**
* wordy_idl/GameServantPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/


// Interface for a Game object when a player joins a game
public abstract class GameServantPOA extends org.omg.PortableServer.Servant
 implements wordy_idl.GameServantOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("submitWord", new java.lang.Integer (0));
    _methods.put ("checkPlayerCount", new java.lang.Integer (1));
    _methods.put ("generateRandomLetters", new java.lang.Integer (2));
    _methods.put ("checkWord", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // wordy_idl/GameServant/submitWord
       {
         try {
           int userId = in.read_long ();
           String word = in.read_string ();
           this.submitWord (userId, word);
           out = $rh.createReply();
         } catch (wordy_idl.InvalidWordException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.InvalidWordExceptionHelper.write (out, $ex);
         } catch (wordy_idl.WordLengthException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.WordLengthExceptionHelper.write (out, $ex);
         } catch (wordy_idl.WrongLetterException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.WrongLetterExceptionHelper.write (out, $ex);
         }
         break;
       }

       case 1:  // wordy_idl/GameServant/checkPlayerCount
       {
         int $result = (int)0;
         $result = this.checkPlayerCount ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // wordy_idl/GameServant/generateRandomLetters
       {
         String $result = null;
         $result = this.generateRandomLetters ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // wordy_idl/GameServant/checkWord
       {
         try {
           String word = in.read_string ();
           String randomLetters = in.read_string ();
           boolean $result = false;
           $result = this.checkWord (word, randomLetters);
           out = $rh.createReply();
           out.write_boolean ($result);
         } catch (wordy_idl.InvalidWordException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.InvalidWordExceptionHelper.write (out, $ex);
         } catch (wordy_idl.WordLengthException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.WordLengthExceptionHelper.write (out, $ex);
         } catch (wordy_idl.WrongLetterException $ex) {
           out = $rh.createExceptionReply ();
           wordy_idl.WrongLetterExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:wordy_idl/GameServant:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public GameServant _this() 
  {
    return GameServantHelper.narrow(
    super._this_object());
  }

  public GameServant _this(org.omg.CORBA.ORB orb) 
  {
    return GameServantHelper.narrow(
    super._this_object(orb));
  }


} // class GameServantPOA
