package wordy_idl;

/**
* wordy_idl/GameMenuServantHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/


// Interface for the Game Menu Servant object
public final class GameMenuServantHolder implements org.omg.CORBA.portable.Streamable
{
  public wordy_idl.GameMenuServant value = null;

  public GameMenuServantHolder ()
  {
  }

  public GameMenuServantHolder (wordy_idl.GameMenuServant initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordy_idl.GameMenuServantHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordy_idl.GameMenuServantHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordy_idl.GameMenuServantHelper.type ();
  }

}
