package wordy_idl;


/**
* wordy_idl/GameServantOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 8:56:36 o'clock PM SGT
*/


// Interface for a Game object when a player joins a game
public interface GameServantOperations 
{
  void submitWord (int userId, String word) throws wordy_idl.InvalidWordException, wordy_idl.WordLengthException, wordy_idl.WrongLetterException;
  int checkPlayerCount ();
  String generateRandomLetters ();
  boolean checkWord (String word, String randomLetters) throws wordy_idl.InvalidWordException, wordy_idl.WordLengthException, wordy_idl.WrongLetterException;
} // interface GameServantOperations
