package wordy_idl;


/**
* wordy_idl/playersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from wordy.idl
* Wednesday, May 10, 2023 6:05:32 o'clock PM SGT
*/

public final class playersHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public playersHolder ()
  {
  }

  public playersHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordy_idl.playersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordy_idl.playersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordy_idl.playersHelper.type ();
  }

}
