#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    May 17, 2023 05:11:50 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import game_menu_frame_support
import best_players_frame_support
import longest_words_frame_support
import in_game_frame_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black' 
_tabfg2 = 'black' 
_tabbg1 = 'grey75' 
_tabbg2 = 'grey89' 
_bgmode = 'light' 

_style_code_ran = 0
def _style_code():
    global _style_code_ran
    if _style_code_ran:
       return
    style = ttk.Style()
    if sys.platform == "win32":
       style.theme_use('winnative')
    style.configure('.',background=_bgcolor)
    style.configure('.',foreground=_fgcolor)
    style.configure('.',font='TkDefaultFont')
    style.map('.',background =
       [('selected', _compcolor), ('active',_ana2color)])
    if _bgmode == 'dark':
       style.map('.',foreground =
         [('selected', 'white'), ('active','white')])
    else:
       style.map('.',foreground =
         [('selected', 'black'), ('active','black')])
    _style_code_ran = 1

class Toplevel1:

    def playGameButton_functionality(self):
        self.top.withdraw()
        in_game_frame_support.main(self.top, self.naming_context, self.game_menu_servant, self.player_id)

    def showBestPlayersButton_functionality(self):
        best_players_frame_support.main(self.game_menu_servant)

    def showLongestWordsButton_functionality(self):
        longest_words_frame_support.main(self.game_menu_servant)


    def exitButton_functionality(self):
        self.login_frame.deiconify()
        self.game_menu_servant.logOut(self.username)
        self.top.destroy()


    def implement_components(self):
        self.exitButton.configure(command=self.exitButton_functionality)
        self.playGameButton.configure(command=self.playGameButton_functionality)
        self.showBestPlayersButton.configure(command=self.showBestPlayersButton_functionality)
        self.showLongestWordsButton.configure(command=self.showLongestWordsButton_functionality)

    def __init__(self, top=None, game_menu_servant=None, login_frame=None, player_id=None, username=None, naming_context=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("466x285+323+146")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Welcome to Wordy")
        top.configure(background="#d9d9d9")

        self.top = top
        self.game_menu_servant = game_menu_servant
        self.login_frame = login_frame
        self.player_id = player_id
        self.username = username
        self.naming_context = naming_context

        _style_code()
        self.top.protocol( 'WM_DELETE_WINDOW' , self.exitButton_functionality)
        self.playGameButton = ttk.Button(self.top)
        self.playGameButton.place(relx=0.429, rely=0.175, height=25, width=76)
        self.playGameButton.configure(takefocus="")
        self.playGameButton.configure(text='''Play Game''')
        self.playGameButton.configure(compound='left')
        self.showBestPlayersButton = ttk.Button(self.top)
        self.showBestPlayersButton.place(relx=0.386, rely=0.351, height=25
                , width=126)
        self.showBestPlayersButton.configure(takefocus="")
        self.showBestPlayersButton.configure(text='''Show Best Players''')
        self.showBestPlayersButton.configure(compound='left')
        self.showLongestWordsButton = ttk.Button(self.top)
        self.showLongestWordsButton.place(relx=0.386, rely=0.526, height=25
                , width=126)
        self.showLongestWordsButton.configure(takefocus="")
        self.showLongestWordsButton.configure(text='''Show Longest Words''')
        self.showLongestWordsButton.configure(compound='left')
        self.exitButton = ttk.Button(self.top)
        self.exitButton.place(relx=0.429, rely=0.702, height=25, width=76)
        self.exitButton.configure(takefocus="")
        self.exitButton.configure(text='''Exit''')
        self.exitButton.configure(compound='left')
        self.implement_components()

def start_up():
    game_menu_frame_support.main()

if __name__ == '__main__':
    game_menu_frame_support.main()




