#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    May 20, 2023 05:34:50 PM CST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *
import os.path

_script = sys.argv[0]
_location = os.path.dirname(_script)

import pending_game_frame_support

_bgcolor = '#d9d9d9'  # X11 color: 'gray85'
_fgcolor = '#000000'  # X11 color: 'black'
_compcolor = 'gray40' # X11 color: #666666
_ana1color = '#c3c3c3' # Closest X11 color: 'gray76'
_ana2color = 'beige' # X11 color: #f5f5dc
_tabfg1 = 'black'
_tabfg2 = 'black'
_tabbg1 = 'grey75'
_tabbg2 = 'grey89'
_bgmode = 'light'

class Toplevel1:

    def update_time_remaining(self, time):
        self.eta_label.configure(text=f"Estimated Time Remaining: {time}")

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''

        top.geometry("409x318+529+166")
        top.minsize(120, 1)
        top.maxsize(1540, 845)
        top.resizable(1,  1)
        top.title("Preparing game...")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.top = top

        self.Frame1 = tk.Frame(self.top)
        self.Frame1.place(relx=0.196, rely=0.22, relheight=0.478, relwidth=0.606)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(highlightbackground="#d9d9d9")
        self.Frame1.configure(highlightcolor="black")
        self.preparing_a_game_label = tk.Label(self.Frame1)
        self.preparing_a_game_label.place(relx=0.121, rely=0.132, height=51
                , width=200)
        self.preparing_a_game_label.configure(activebackground="#f9f9f9")
        self.preparing_a_game_label.configure(anchor='w')
        self.preparing_a_game_label.configure(background="#d9d9d9")
        self.preparing_a_game_label.configure(compound='left')
        self.preparing_a_game_label.configure(disabledforeground="#a3a3a3")
        self.preparing_a_game_label.configure(foreground="#000000")
        self.preparing_a_game_label.configure(highlightbackground="#d9d9d9")
        self.preparing_a_game_label.configure(highlightcolor="black")
        self.preparing_a_game_label.configure(text='''Preparing a game. Please wait...''')
        self.eta_label = tk.Label(self.Frame1)
        self.eta_label.place(relx=0.081, rely=0.592, height=41, width=214)
        self.eta_label.configure(activebackground="#f9f9f9")
        self.eta_label.configure(anchor='w')
        self.eta_label.configure(background="#d9d9d9")
        self.eta_label.configure(compound='left')
        self.eta_label.configure(disabledforeground="#a3a3a3")
        self.eta_label.configure(foreground="#000000")
        self.eta_label.configure(highlightbackground="#d9d9d9")
        self.eta_label.configure(highlightcolor="black")
        self.eta_label.configure(text='''Estimated Time Remaining: Computing''')

def start_up():
    pending_game_frame_support.main()

if __name__ == '__main__':
    pending_game_frame_support.main()
