# Python stubs generated by omniidl from Wordy.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "wordy_idl"
#
__name__ = "wordy_idl"
_0_wordy_idl = omniORB.openModule("wordy_idl", r"Wordy.idl")
_0_wordy_idl__POA = omniORB.openModule("wordy_idl__POA", r"Wordy.idl")


# exception InvalidPasswordException
_0_wordy_idl.InvalidPasswordException = omniORB.newEmptyClass()
class InvalidPasswordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/InvalidPasswordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.InvalidPasswordException = InvalidPasswordException
_0_wordy_idl._d_InvalidPasswordException  = (omniORB.tcInternal.tv_except, InvalidPasswordException, InvalidPasswordException._NP_RepositoryId, "InvalidPasswordException")
_0_wordy_idl._tc_InvalidPasswordException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_InvalidPasswordException)
omniORB.registerType(InvalidPasswordException._NP_RepositoryId, _0_wordy_idl._d_InvalidPasswordException, _0_wordy_idl._tc_InvalidPasswordException)
del InvalidPasswordException

# exception NoUserFoundException
_0_wordy_idl.NoUserFoundException = omniORB.newEmptyClass()
class NoUserFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/NoUserFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.NoUserFoundException = NoUserFoundException
_0_wordy_idl._d_NoUserFoundException  = (omniORB.tcInternal.tv_except, NoUserFoundException, NoUserFoundException._NP_RepositoryId, "NoUserFoundException")
_0_wordy_idl._tc_NoUserFoundException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_NoUserFoundException)
omniORB.registerType(NoUserFoundException._NP_RepositoryId, _0_wordy_idl._d_NoUserFoundException, _0_wordy_idl._tc_NoUserFoundException)
del NoUserFoundException

# exception LoggedInException
_0_wordy_idl.LoggedInException = omniORB.newEmptyClass()
class LoggedInException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/LoggedInException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.LoggedInException = LoggedInException
_0_wordy_idl._d_LoggedInException  = (omniORB.tcInternal.tv_except, LoggedInException, LoggedInException._NP_RepositoryId, "LoggedInException")
_0_wordy_idl._tc_LoggedInException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_LoggedInException)
omniORB.registerType(LoggedInException._NP_RepositoryId, _0_wordy_idl._d_LoggedInException, _0_wordy_idl._tc_LoggedInException)
del LoggedInException

# exception IncompleteCredentialsException
_0_wordy_idl.IncompleteCredentialsException = omniORB.newEmptyClass()
class IncompleteCredentialsException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/IncompleteCredentialsException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.IncompleteCredentialsException = IncompleteCredentialsException
_0_wordy_idl._d_IncompleteCredentialsException  = (omniORB.tcInternal.tv_except, IncompleteCredentialsException, IncompleteCredentialsException._NP_RepositoryId, "IncompleteCredentialsException")
_0_wordy_idl._tc_IncompleteCredentialsException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_IncompleteCredentialsException)
omniORB.registerType(IncompleteCredentialsException._NP_RepositoryId, _0_wordy_idl._d_IncompleteCredentialsException, _0_wordy_idl._tc_IncompleteCredentialsException)
del IncompleteCredentialsException

# exception NoPlayersJoinedException
_0_wordy_idl.NoPlayersJoinedException = omniORB.newEmptyClass()
class NoPlayersJoinedException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/NoPlayersJoinedException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.NoPlayersJoinedException = NoPlayersJoinedException
_0_wordy_idl._d_NoPlayersJoinedException  = (omniORB.tcInternal.tv_except, NoPlayersJoinedException, NoPlayersJoinedException._NP_RepositoryId, "NoPlayersJoinedException")
_0_wordy_idl._tc_NoPlayersJoinedException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_NoPlayersJoinedException)
omniORB.registerType(NoPlayersJoinedException._NP_RepositoryId, _0_wordy_idl._d_NoPlayersJoinedException, _0_wordy_idl._tc_NoPlayersJoinedException)
del NoPlayersJoinedException

# exception NoGameFoundException
_0_wordy_idl.NoGameFoundException = omniORB.newEmptyClass()
class NoGameFoundException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/NoGameFoundException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.NoGameFoundException = NoGameFoundException
_0_wordy_idl._d_NoGameFoundException  = (omniORB.tcInternal.tv_except, NoGameFoundException, NoGameFoundException._NP_RepositoryId, "NoGameFoundException")
_0_wordy_idl._tc_NoGameFoundException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_NoGameFoundException)
omniORB.registerType(NoGameFoundException._NP_RepositoryId, _0_wordy_idl._d_NoGameFoundException, _0_wordy_idl._tc_NoGameFoundException)
del NoGameFoundException

# exception InvalidWordException
_0_wordy_idl.InvalidWordException = omniORB.newEmptyClass()
class InvalidWordException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/InvalidWordException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.InvalidWordException = InvalidWordException
_0_wordy_idl._d_InvalidWordException  = (omniORB.tcInternal.tv_except, InvalidWordException, InvalidWordException._NP_RepositoryId, "InvalidWordException")
_0_wordy_idl._tc_InvalidWordException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_InvalidWordException)
omniORB.registerType(InvalidWordException._NP_RepositoryId, _0_wordy_idl._d_InvalidWordException, _0_wordy_idl._tc_InvalidWordException)
del InvalidWordException

# exception WordLengthException
_0_wordy_idl.WordLengthException = omniORB.newEmptyClass()
class WordLengthException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/WordLengthException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.WordLengthException = WordLengthException
_0_wordy_idl._d_WordLengthException  = (omniORB.tcInternal.tv_except, WordLengthException, WordLengthException._NP_RepositoryId, "WordLengthException")
_0_wordy_idl._tc_WordLengthException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_WordLengthException)
omniORB.registerType(WordLengthException._NP_RepositoryId, _0_wordy_idl._d_WordLengthException, _0_wordy_idl._tc_WordLengthException)
del WordLengthException

# exception WrongLetterException
_0_wordy_idl.WrongLetterException = omniORB.newEmptyClass()
class WrongLetterException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/WrongLetterException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.WrongLetterException = WrongLetterException
_0_wordy_idl._d_WrongLetterException  = (omniORB.tcInternal.tv_except, WrongLetterException, WrongLetterException._NP_RepositoryId, "WrongLetterException")
_0_wordy_idl._tc_WrongLetterException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_WrongLetterException)
omniORB.registerType(WrongLetterException._NP_RepositoryId, _0_wordy_idl._d_WrongLetterException, _0_wordy_idl._tc_WrongLetterException)
del WrongLetterException

# exception PendingGameException
_0_wordy_idl.PendingGameException = omniORB.newEmptyClass()
class PendingGameException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/PendingGameException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.PendingGameException = PendingGameException
_0_wordy_idl._d_PendingGameException  = (omniORB.tcInternal.tv_except, PendingGameException, PendingGameException._NP_RepositoryId, "PendingGameException")
_0_wordy_idl._tc_PendingGameException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_PendingGameException)
omniORB.registerType(PendingGameException._NP_RepositoryId, _0_wordy_idl._d_PendingGameException, _0_wordy_idl._tc_PendingGameException)
del PendingGameException

# exception NoWinnerException
_0_wordy_idl.NoWinnerException = omniORB.newEmptyClass()
class NoWinnerException (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordy_idl/NoWinnerException:1.0"

    def __init__(self):
        CORBA.UserException.__init__(self)

_0_wordy_idl.NoWinnerException = NoWinnerException
_0_wordy_idl._d_NoWinnerException  = (omniORB.tcInternal.tv_except, NoWinnerException, NoWinnerException._NP_RepositoryId, "NoWinnerException")
_0_wordy_idl._tc_NoWinnerException = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_NoWinnerException)
omniORB.registerType(NoWinnerException._NP_RepositoryId, _0_wordy_idl._d_NoWinnerException, _0_wordy_idl._tc_NoWinnerException)
del NoWinnerException

# typedef ... playerRecord
class playerRecord:
    _NP_RepositoryId = "IDL:wordy_idl/playerRecord:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordy_idl.playerRecord = playerRecord
_0_wordy_idl._d_playerRecord  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_wordy_idl._ad_playerRecord = (omniORB.tcInternal.tv_alias, playerRecord._NP_RepositoryId, "playerRecord", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_wordy_idl._tc_playerRecord = omniORB.tcInternal.createTypeCode(_0_wordy_idl._ad_playerRecord)
omniORB.registerType(playerRecord._NP_RepositoryId, _0_wordy_idl._ad_playerRecord, _0_wordy_idl._tc_playerRecord)
del playerRecord

# typedef ... bestPlayers
class bestPlayers:
    _NP_RepositoryId = "IDL:wordy_idl/bestPlayers:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordy_idl.bestPlayers = bestPlayers
_0_wordy_idl._d_bestPlayers  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0)
_0_wordy_idl._ad_bestPlayers = (omniORB.tcInternal.tv_alias, bestPlayers._NP_RepositoryId, "bestPlayers", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0))
_0_wordy_idl._tc_bestPlayers = omniORB.tcInternal.createTypeCode(_0_wordy_idl._ad_bestPlayers)
omniORB.registerType(bestPlayers._NP_RepositoryId, _0_wordy_idl._ad_bestPlayers, _0_wordy_idl._tc_bestPlayers)
del bestPlayers

# typedef ... longestWords
class longestWords:
    _NP_RepositoryId = "IDL:wordy_idl/longestWords:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordy_idl.longestWords = longestWords
_0_wordy_idl._d_longestWords  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0)
_0_wordy_idl._ad_longestWords = (omniORB.tcInternal.tv_alias, longestWords._NP_RepositoryId, "longestWords", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0))
_0_wordy_idl._tc_longestWords = omniORB.tcInternal.createTypeCode(_0_wordy_idl._ad_longestWords)
omniORB.registerType(longestWords._NP_RepositoryId, _0_wordy_idl._ad_longestWords, _0_wordy_idl._tc_longestWords)
del longestWords

# typedef ... randomLetters
class randomLetters:
    _NP_RepositoryId = "IDL:wordy_idl/randomLetters:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordy_idl.randomLetters = randomLetters
_0_wordy_idl._d_randomLetters  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0)
_0_wordy_idl._ad_randomLetters = (omniORB.tcInternal.tv_alias, randomLetters._NP_RepositoryId, "randomLetters", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0))
_0_wordy_idl._tc_randomLetters = omniORB.tcInternal.createTypeCode(_0_wordy_idl._ad_randomLetters)
omniORB.registerType(randomLetters._NP_RepositoryId, _0_wordy_idl._ad_randomLetters, _0_wordy_idl._tc_randomLetters)
del randomLetters

# typedef ... usersAndWins
class usersAndWins:
    _NP_RepositoryId = "IDL:wordy_idl/usersAndWins:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordy_idl.usersAndWins = usersAndWins
_0_wordy_idl._d_usersAndWins  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0)
_0_wordy_idl._ad_usersAndWins = (omniORB.tcInternal.tv_alias, usersAndWins._NP_RepositoryId, "usersAndWins", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordy_idl/playerRecord:1.0"], 0))
_0_wordy_idl._tc_usersAndWins = omniORB.tcInternal.createTypeCode(_0_wordy_idl._ad_usersAndWins)
omniORB.registerType(usersAndWins._NP_RepositoryId, _0_wordy_idl._ad_usersAndWins, _0_wordy_idl._tc_usersAndWins)
del usersAndWins

# interface GameMenuServant
_0_wordy_idl._d_GameMenuServant = (omniORB.tcInternal.tv_objref, "IDL:wordy_idl/GameMenuServant:1.0", "GameMenuServant")
omniORB.typeMapping["IDL:wordy_idl/GameMenuServant:1.0"] = _0_wordy_idl._d_GameMenuServant
_0_wordy_idl.GameMenuServant = omniORB.newEmptyClass()
class GameMenuServant :
    _NP_RepositoryId = _0_wordy_idl._d_GameMenuServant[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_wordy_idl.GameMenuServant = GameMenuServant
_0_wordy_idl._tc_GameMenuServant = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_GameMenuServant)
omniORB.registerType(GameMenuServant._NP_RepositoryId, _0_wordy_idl._d_GameMenuServant, _0_wordy_idl._tc_GameMenuServant)

# GameMenuServant operations and attributes
GameMenuServant._d_logIn = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_wordy_idl.InvalidPasswordException._NP_RepositoryId: _0_wordy_idl._d_InvalidPasswordException, _0_wordy_idl.NoUserFoundException._NP_RepositoryId: _0_wordy_idl._d_NoUserFoundException, _0_wordy_idl.LoggedInException._NP_RepositoryId: _0_wordy_idl._d_LoggedInException, _0_wordy_idl.IncompleteCredentialsException._NP_RepositoryId: _0_wordy_idl._d_IncompleteCredentialsException})
GameMenuServant._d_createGame = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), None)
GameMenuServant._d_joinGame = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_long, ), {_0_wordy_idl.NoGameFoundException._NP_RepositoryId: _0_wordy_idl._d_NoGameFoundException})
GameMenuServant._d_getBestPlayers = ((), (omniORB.typeMapping["IDL:wordy_idl/bestPlayers:1.0"], ), None)
GameMenuServant._d_getLongestWords = ((), (omniORB.typeMapping["IDL:wordy_idl/longestWords:1.0"], ), None)
GameMenuServant._d_logOut = (((omniORB.tcInternal.tv_string,0), ), (), None)

# GameMenuServant object reference
class _objref_GameMenuServant (CORBA.Object):
    _NP_RepositoryId = GameMenuServant._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def logIn(self, *args):
        return self._obj.invoke("logIn", _0_wordy_idl.GameMenuServant._d_logIn, args)

    def createGame(self, *args):
        return self._obj.invoke("createGame", _0_wordy_idl.GameMenuServant._d_createGame, args)

    def joinGame(self, *args):
        return self._obj.invoke("joinGame", _0_wordy_idl.GameMenuServant._d_joinGame, args)

    def getBestPlayers(self, *args):
        return self._obj.invoke("getBestPlayers", _0_wordy_idl.GameMenuServant._d_getBestPlayers, args)

    def getLongestWords(self, *args):
        return self._obj.invoke("getLongestWords", _0_wordy_idl.GameMenuServant._d_getLongestWords, args)

    def logOut(self, *args):
        return self._obj.invoke("logOut", _0_wordy_idl.GameMenuServant._d_logOut, args)

omniORB.registerObjref(GameMenuServant._NP_RepositoryId, _objref_GameMenuServant)
_0_wordy_idl._objref_GameMenuServant = _objref_GameMenuServant
del GameMenuServant, _objref_GameMenuServant

# GameMenuServant skeleton
__name__ = "wordy_idl__POA"
class GameMenuServant (PortableServer.Servant):
    _NP_RepositoryId = _0_wordy_idl.GameMenuServant._NP_RepositoryId


    _omni_op_d = {"logIn": _0_wordy_idl.GameMenuServant._d_logIn, "createGame": _0_wordy_idl.GameMenuServant._d_createGame, "joinGame": _0_wordy_idl.GameMenuServant._d_joinGame, "getBestPlayers": _0_wordy_idl.GameMenuServant._d_getBestPlayers, "getLongestWords": _0_wordy_idl.GameMenuServant._d_getLongestWords, "logOut": _0_wordy_idl.GameMenuServant._d_logOut}

GameMenuServant._omni_skeleton = GameMenuServant
_0_wordy_idl__POA.GameMenuServant = GameMenuServant
omniORB.registerSkeleton(GameMenuServant._NP_RepositoryId, GameMenuServant)
del GameMenuServant
__name__ = "wordy_idl"

# interface GameServant
_0_wordy_idl._d_GameServant = (omniORB.tcInternal.tv_objref, "IDL:wordy_idl/GameServant:1.0", "GameServant")
omniORB.typeMapping["IDL:wordy_idl/GameServant:1.0"] = _0_wordy_idl._d_GameServant
_0_wordy_idl.GameServant = omniORB.newEmptyClass()
class GameServant :
    _NP_RepositoryId = _0_wordy_idl._d_GameServant[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_wordy_idl.GameServant = GameServant
_0_wordy_idl._tc_GameServant = omniORB.tcInternal.createTypeCode(_0_wordy_idl._d_GameServant)
omniORB.registerType(GameServant._NP_RepositoryId, _0_wordy_idl._d_GameServant, _0_wordy_idl._tc_GameServant)

# GameServant operations and attributes
GameServant._d_gameCanStart = ((), (omniORB.tcInternal.tv_boolean, ), {_0_wordy_idl.NoPlayersJoinedException._NP_RepositoryId: _0_wordy_idl._d_NoPlayersJoinedException, _0_wordy_idl.PendingGameException._NP_RepositoryId: _0_wordy_idl._d_PendingGameException})
GameServant._d_gameIsFinished = ((), (omniORB.tcInternal.tv_boolean, ), None)
GameServant._d_submitWord = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_wordy_idl.InvalidWordException._NP_RepositoryId: _0_wordy_idl._d_InvalidWordException, _0_wordy_idl.WordLengthException._NP_RepositoryId: _0_wordy_idl._d_WordLengthException, _0_wordy_idl.WrongLetterException._NP_RepositoryId: _0_wordy_idl._d_WrongLetterException})
GameServant._d_checkPlayerCount = ((), (omniORB.tcInternal.tv_long, ), None)
GameServant._d_getRemainingPendingTime = ((), (omniORB.tcInternal.tv_longlong, ), None)
GameServant._d_getRemainingReadyTime = ((), (omniORB.tcInternal.tv_longlong, ), None)
GameServant._d_getRemainingRoundTime = ((), (omniORB.tcInternal.tv_longlong, ), None)
GameServant._d_getRemainingResultsTime = ((), (omniORB.tcInternal.tv_longlong, ), None)
GameServant._d_getRoundWinnerName = ((), ((omniORB.tcInternal.tv_string,0), ), None)
GameServant._d_leaveGame = ((omniORB.tcInternal.tv_long, ), (), None)
GameServant._d_youAreWinner = ((omniORB.tcInternal.tv_long, ), (omniORB.tcInternal.tv_boolean, ), {_0_wordy_idl.NoWinnerException._NP_RepositoryId: _0_wordy_idl._d_NoWinnerException})
GameServant._d_getUsersAndWins = ((), (omniORB.typeMapping["IDL:wordy_idl/usersAndWins:1.0"], ), None)
GameServant._d_getLetters = ((), (omniORB.typeMapping["IDL:wordy_idl/randomLetters:1.0"], ), None)

# GameServant object reference
class _objref_GameServant (CORBA.Object):
    _NP_RepositoryId = GameServant._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def gameCanStart(self, *args):
        return self._obj.invoke("gameCanStart", _0_wordy_idl.GameServant._d_gameCanStart, args)

    def gameIsFinished(self, *args):
        return self._obj.invoke("gameIsFinished", _0_wordy_idl.GameServant._d_gameIsFinished, args)

    def submitWord(self, *args):
        return self._obj.invoke("submitWord", _0_wordy_idl.GameServant._d_submitWord, args)

    def checkPlayerCount(self, *args):
        return self._obj.invoke("checkPlayerCount", _0_wordy_idl.GameServant._d_checkPlayerCount, args)

    def getRemainingPendingTime(self, *args):
        return self._obj.invoke("getRemainingPendingTime", _0_wordy_idl.GameServant._d_getRemainingPendingTime, args)

    def getRemainingReadyTime(self, *args):
        return self._obj.invoke("getRemainingReadyTime", _0_wordy_idl.GameServant._d_getRemainingReadyTime, args)

    def getRemainingRoundTime(self, *args):
        return self._obj.invoke("getRemainingRoundTime", _0_wordy_idl.GameServant._d_getRemainingRoundTime, args)

    def getRemainingResultsTime(self, *args):
        return self._obj.invoke("getRemainingResultsTime", _0_wordy_idl.GameServant._d_getRemainingResultsTime, args)

    def getRoundWinnerName(self, *args):
        return self._obj.invoke("getRoundWinnerName", _0_wordy_idl.GameServant._d_getRoundWinnerName, args)

    def leaveGame(self, *args):
        return self._obj.invoke("leaveGame", _0_wordy_idl.GameServant._d_leaveGame, args)

    def youAreWinner(self, *args):
        return self._obj.invoke("youAreWinner", _0_wordy_idl.GameServant._d_youAreWinner, args)

    def getUsersAndWins(self, *args):
        return self._obj.invoke("getUsersAndWins", _0_wordy_idl.GameServant._d_getUsersAndWins, args)

    def getLetters(self, *args):
        return self._obj.invoke("getLetters", _0_wordy_idl.GameServant._d_getLetters, args)

omniORB.registerObjref(GameServant._NP_RepositoryId, _objref_GameServant)
_0_wordy_idl._objref_GameServant = _objref_GameServant
del GameServant, _objref_GameServant

# GameServant skeleton
__name__ = "wordy_idl__POA"
class GameServant (PortableServer.Servant):
    _NP_RepositoryId = _0_wordy_idl.GameServant._NP_RepositoryId


    _omni_op_d = {"gameCanStart": _0_wordy_idl.GameServant._d_gameCanStart, "gameIsFinished": _0_wordy_idl.GameServant._d_gameIsFinished, "submitWord": _0_wordy_idl.GameServant._d_submitWord, "checkPlayerCount": _0_wordy_idl.GameServant._d_checkPlayerCount, "getRemainingPendingTime": _0_wordy_idl.GameServant._d_getRemainingPendingTime, "getRemainingReadyTime": _0_wordy_idl.GameServant._d_getRemainingReadyTime, "getRemainingRoundTime": _0_wordy_idl.GameServant._d_getRemainingRoundTime, "getRemainingResultsTime": _0_wordy_idl.GameServant._d_getRemainingResultsTime, "getRoundWinnerName": _0_wordy_idl.GameServant._d_getRoundWinnerName, "leaveGame": _0_wordy_idl.GameServant._d_leaveGame, "youAreWinner": _0_wordy_idl.GameServant._d_youAreWinner, "getUsersAndWins": _0_wordy_idl.GameServant._d_getUsersAndWins, "getLetters": _0_wordy_idl.GameServant._d_getLetters}

GameServant._omni_skeleton = GameServant
_0_wordy_idl__POA.GameServant = GameServant
omniORB.registerSkeleton(GameServant._NP_RepositoryId, GameServant)
del GameServant
__name__ = "wordy_idl"

#
# End of module "wordy_idl"
#
__name__ = "Wordy_idl"

_exported_modules = ( "wordy_idl", )

# The end.
